CREATE TABLE [dbo].[Call]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1, 1),
	[CallNumber] int not null,
	[PatientId] int not null,
	[AmbulanceBrigadeId] int not null,
	[DispatcherId] int not null,
	[LinkedCallId] int,
	[IsIncidential] bit not null,
	[ResultId] int not null,
	[DiagnosisId] int not null,
	[DateTimeReception] datetime not null,
	[TransferDateTime] datetime not null,
	[ArrivalDateTime] datetime not null,
	[DepartureDateTime] datetime not null,
	[ComebackDateTime] datetime not null,
	[TransferingDispatcherId] int,
	[ProcessingDispatcherId] int,
	[KilometrageBefore] int not null,
	[KilometrageAfter] int not null,
	[PlaceId] int not null,
	[CallNotes] varchar(max),
	[CallType] tinyint not null,
	[IsProcessed] bit not null,

	Constraint [FK_Patient] foreign key (PatientId) references Patients (Id),
	Constraint [FK_AmbulanceBrigade] foreign key (AmbulanceBrigadeId) references AmbulanceBrigades (Id),
	Constraint [FK_Dispatcher] foreign key (DispatcherId) references Dispatchers (Id),
	Constraint [FK_LinkedCall] foreign key (LinkedCallId) references [dbo].[Call] (Id),
	Constraint [FK_Result] foreign key (ResultId) references Results (Id),
	Constraint [FK_Diagnosis] foreign key (DiagnosisId) references Diagnosies (Id),
	Constraint [FK_TransfDispatcher] foreign key (TransferingDispatcherId) references Dispatchers (Id),
	Constraint [FK_ProcessDispatcher] foreign key (ProcessingDispatcherId) references Dispatchers (Id),
	Constraint [FK_Place] foreign key (PlaceId) references Places (Id),
)
