CREATE TABLE [dbo].[CallAdditionalInfo]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1, 1),
	[CallId] int not null,
	[Type] tinyint not null,
	[UnsuccessfulDeparture] tinyint not null,
	[DateAndTimeType] datetime not null,
	[DateAndTimeDescription] varchar(500) NOT NULL,
	[InjuryType] tinyint not null,
	[InjuryTypeDescription] varchar(200),
	[Сomplaints] varchar(max) not null,
	[Anamnesis] varchar(max) not null,
	[ListedDiseases] varchar(max) not null,
	[ObstetricAndGynecologicalAnamnesis] varchar(max),
	[Allergy] varchar(max),
	[CommonState] tinyint not null,
	[Position] tinyint not null,
	[Behaviour] tinyint not null,
	[BehaviourDescription] varchar(500),
	[GlasgowComaScale] tinyint not null,
	[Сonscience] tinyint not null,
	[PupilCondition] tinyint not null,
	[ReactionToLight] bit not null,
	[SpeechState] tinyint not null,
	[SpeechStateDescription] varchar(500),
	[Gait] tinyint not null,
	[GaitDescription] varchar(500),
	[FaceCondition] bit not null,
	[Nystagmus] tinyint not null,
	[MuscleTone] tinyint not null,

	Constraint [FK_Call] foreign key (CallId) references [dbo].[Call] (Id),
)
