CREATE TABLE [dbo].[CallAdditionalInfo]
(
	[Id] INT NOT NULL PRIMARY KEY identity(1, 1),
	[CallId] int not null,
	[Type] tinyint not null,
	[UnsuccessfulDeparture] tinyint not null,
	[DateAndTimeType] datetime not null,
	[DateAndTimeDescription] nvarchar(500) NOT NULL,
	[InjuryType] tinyint not null,
	[InjuryTypeDescription] nvarchar(200),
	[Сomplaints] nvarchar(max) not null,
	[Anamnesis] nvarchar(max) not null,
	[ListedDiseases] nvarchar(max) not null,
	[ObstetricAndGynecologicalAnamnesis] nvarchar(max),
	[Allergy] nvarchar(max),
	[CommonState] tinyint not null,
	[Position] tinyint not null,
	[Behaviour] tinyint not null,
	[BehaviourDescription] nvarchar(500),
	[GlasgowComaScale] tinyint not null,
	[Сonscience] tinyint not null,
	[PupilCondition] tinyint not null,
	[ReactionToLight] bit not null,
	[SpeechState] tinyint not null,
	[SpeechStateDescription] nvarchar(500),
	[Gait] tinyint not null,
	[GaitDescription] nvarchar(500),
	[FaceCondition] bit not null,
	[Nystagmus] tinyint not null,
	[MuscleTone] tinyint not null,

	Constraint [FK_Call] foreign key (CallId) references [dbo].[Call] (Id),
)
